version: "3.11" # Docker ComposeAPI
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=youtube
      - DB_USER=jclee5419
      - DB_PASS=password123
    depends_on:
      - db

  db: #PostgreSQL Database
    image: postgresql:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/dat
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=jclee5419
      - POSTGRES_PASSWORD=password123